### ISSUE TITLE
How to clone and compile FluentSharp in VisualStudio 2013

### ISSUE THREAD

**Issue by DinisCruz** [o2platform/FluentSharp#24]
Here are the steps required to close and compile the FluentSharp projects (and the main O2 Platform project)

**1)** from https://github.com/o2platform/FluentSharp copy the the git clone Url: git@github.com:o2platform/FluentSharp.git or https://github.com/o2platform/FluentSharp.git

Note if you want to submit changes (or have your own version) you will need to create a Fork (which you can via the top-right 'Fork' button)):

![image](https://cloud.githubusercontent.com/assets/656739/3868177/16d8c238-2029-11e4-964a-b3351008636a.png)

**2)** on your windows VM/Box create a folder to hold the git clone:

![image](https://cloud.githubusercontent.com/assets/656739/3868182/515cff1e-2029-11e4-89a6-5a94175fd708.png)

**3)** clone the repo (note that the 'Recursive' checkbox is checked )
![image](https://cloud.githubusercontent.com/assets/656739/3868183/7024dfca-2029-11e4-931f-e65d506e8766.png)

**4)** wait a little bit while the clone happens:

![image](https://cloud.githubusercontent.com/assets/656739/3868186/8a0efa2e-2029-11e4-8bb2-7766457a5e0b.png)

... after the main repo is cloned, there are a couple submodules to clone:

![image](https://cloud.githubusercontent.com/assets/656739/3868191/dfc02934-2029-11e4-89d2-bdc84c3ca829.png)

... and if all goes well, this is what the target folder (and clone log) should look like:

![image](https://cloud.githubusercontent.com/assets/656739/3868192/141185ca-202a-11e4-8e9f-55ac074762ab.png)

**5)** open the **FluentSharp.sln** file, which after opening should look like this:

![image](https://cloud.githubusercontent.com/assets/656739/3868198/9d83ec8a-202a-11e4-961d-ab91364bf3f9.png)

**6)** ensure that that the **FluentSharp.O2Platform** is **Set as StartUp Project"" 

![image](https://cloud.githubusercontent.com/assets/656739/3868200/bc04c42c-202a-11e4-981c-5af576b1e78d.png)

**7)** build the solution:

![image](https://cloud.githubusercontent.com/assets/656739/3868204/f6c303b2-202a-11e4-8924-9280b679b798.png)

.... which should compile with no errors:

![image](https://cloud.githubusercontent.com/assets/656739/3868239/4374e3fe-202d-11e4-8eaf-64f1dbee817a.png)

**8)** Run/Debug the solution

![image](https://cloud.githubusercontent.com/assets/656739/3868243/5e9d4d42-202d-11e4-8b3c-806034857da2.png)

... which should look like this:

![image](https://cloud.githubusercontent.com/assets/656739/3868245/772bf570-202d-11e4-9cf4-9d6be36e1ac0.png)

**Comment by CallMeSteve** [comment]
I still get a lot of errors during compilation (step 7). There's a lot of files missing. Mainly assemblies. The one I can't seem to find anywhere is "ICSharpCode.NRefactory.Ast.dll". Another thing that's missing is FluentSharp.O2Platform.exe. 
Can you please advice on how I should proceed?

**Comment by DinisCruz** [comment]
Sorry, just saw this, are you still having this prob?
