### ISSUE TITLE
Change sub-modules to be fetched using https instead of SSH

### ISSUE THREAD

**Issue by roman87** [o2platform/FluentSharp#36]
Since submodules are public repositories, it is not necessary to require an overhead of ssh authentication for users wanting to fetch the whole FluentSharp repo. Kinda defeats the purpose of public:)
Specifically change:
[submodule "FluentSharp_Fork.CassiniDev"]
	path = FluentSharp_Fork.CassiniDev
	url = git@github.com:o2platform/FluentSharp_Fork.CassiniDev.git

To
[submodule "FluentSharp_Fork.CassiniDev"]
	path = FluentSharp_Fork.CassiniDev
	url = https://github.com/o2platform/FluentSharp_Fork.CassiniDev.git

**Comment by DinisCruz** [comment]
Actually we can still use the git mode for public repos (like this one), see here https://github.com/TeamMentor/TM_4_0_QA/commit/aba9937f632c34ab93e0a6daaa9fa22512516d6f

basically we need to use 

git:github.com/o2platform/FluentSharp_Fork.CassiniDev.git

**Comment by roman87** [comment]
not really. the git mode assumes SSH and looks for a key regardless if the repo is public.

**Comment by DinisCruz** [comment]
not if you use the format git//:github.com/o2platform/FluentSharp_Fork.CassiniDev.git 

See this info on http://docs.travis-ci.com/user/build-configuration/

![image](https://cloud.githubusercontent.com/assets/656739/5618462/2a647e70-9511-11e4-87ed-0f0df5efac29.png)

**Comment by roman87** [comment]
Hmm.. ok we have to try this with TC
